name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc, gcc-8, gcc-9, gcc-10 ]
    steps:
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install gettext gcc-8 gcc-9 gcc-10 libyajl-dev libsqlite3-dev
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: JSON test
        run: ./fmp2json test/data/fp3/government.FP3 -
      - name: SQLite test
        run: ./fmp2sqlite test/data/fp3/government.FP3 government.sqlite
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: brew install automake yajl libxlsxwriter
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: JSON test
        run: ./fmp2json test/data/fp3/government.FP3 -
      - name: SQLite test
        run: ./fmp2sqlite test/data/fp3/government.FP3 government.sqlite
      - name: Excel test
        run: ./fmp2excel test/data/fp3/government.FP3 government.xlsx
